name: Deploy To Render
on:
  workflow_dispatch:
    inputs:
      deploy-to-ui:
        type: boolean
        description: 'Deploy UI?'
        default: true
      deploy-to-api:
        type: boolean
        description: 'Deploy API?'
        default: true
      deploy-to-idp_api:
        type: boolean
        description: 'Deploy IDP API?'
        default: true
      deploy-to-storybook:
        type: boolean
        description: 'Deploy Storybook?'
        default: true
jobs:
  deploy-ui-to-render:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.deploy-to-ui == 'true'}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Deploy
        run: |
          curl ${{ secrets.RENDER_DEPLOYMENT_HOOK_UI }}

  deploy-api-to-render:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.deploy-to-api == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Deploy
        run: |
          curl ${{ secrets.RENDER_DEPLOYMENT_HOOK_API }}

  deploy-idp_api-to-render:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.deploy-to-idp_api == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Deploy
        run: |
          curl ${{ secrets.RENDER_DEPLOYMENT_HOOK_IDP_API }}

  deploy-story-to-render:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.deploy-to-storybook == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Deploy
        run: |
          curl ${{ secrets.RENDER_DEPLOYMENT_HOOK_STORYBOOK }}
